name: tinting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-un: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - user: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn install
      - name: build project
        run: yarn build
      - name: linting typescript
        run: yarn lint:ts
      - name: linting css
        run: yarn lint:scss
      - name: testing
        run: yarn test